---
title: "DP-DELABAERE"
author: "Camille DELABAERE"
date: "2024-11-19"
output: html_document
---

## Group members :

Keve Toth ; Jakov Cancar ; Camille Delabaere

### 1/ Select the data.

Cooperation between arbuscular mycorrhizal fungi and plant growth-promoting bacteria and their effects on plant growth and soil quality. <https://peerj.com/articles/13080/#supp-1>

### 2/ Define the objectives.

To analyse if arbuscular mycorrhizal fungi *AMF* & plant growth-promoting rhizobacteria *PGRB* have any synergy effects on nutrients uptakes or plant growth.

### 3/ Define the main hypotheses.

We hypothesized that: (1) AMF and PGPR could mutually symbiose and enhance the plant growth of Elymus nutans Griseb, and (2) the co-existence of AMF and PGPR could improve plant traits and soil quality better than their individual applications.

### 4/ Analyses needed or intended.

Correlation analyses, ANOVA analyse, and some multivariate analyses.

We plan to start with each variable analyses separately then ANOVA analyses we'll combine these small results analyses with the knowledge acquire from the article chosen to define the larger scale multivariate analyses. These might be a relationship between soil nutrients/quality and plant size measurements (multiple roots measurements and above ground biomass).
